//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.MallaCursos = new HashSet<MallaCurso>();
        }
    
        public string Codigo { get; set; }
        public string Asignatura { get; set; }
        public string Prerequisito { get; set; }
        public string Color { get; set; }
        public Nullable<int> Semestre { get; set; }
        public Nullable<int> Creditos { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> TPS { get; set; }
        public Nullable<int> TIS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MallaCurso> MallaCursos { get; set; }
    }
}
