//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MallaCurso
    {
        public int MallaId { get; set; }
        public string CursoCodigo { get; set; }
        public int Semestre { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Malla Malla { get; set; }
    }
}
