//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MallaDBEntities2 : DbContext
    {
        public MallaDBEntities2()
            : base("name=MallaDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<MallaCurso> MallaCursos { get; set; }
        public virtual DbSet<Malla> Mallas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
