//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Electiva
    {
        public string Codigo { get; set; }
        public string Asignatura { get; set; }
        public string Color { get; set; }
        public Nullable<int> Creditos { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> TPS { get; set; }
        public Nullable<int> TIS { get; set; }
    }
}
