//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MicrodisenoRole
    {
        public int Id { get; set; }
        public string CursoCodigo { get; set; }
        public int CreadorId { get; set; }
        public int AvalId { get; set; }
    }
}
