//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Microdiseno
    {
        public int Id { get; set; }
        public string CursoCodigo { get; set; }
        public string Semestre { get; set; }
        public string Facultad { get; set; }
        public string Modalidad { get; set; }
        public string TipoCredito { get; set; }
        public string TipoAsignatura { get; set; }
        public string Estado { get; set; }
        public string Version { get; set; }
        public string ElaboradoPor { get; set; }
        public string RevisadoPor { get; set; }
        public string AprobadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string ObservacionesRechazo { get; set; }
        public string ContenidoJSON { get; set; }
        public bool VisibleParaTodos { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaAval { get; set; }
    }
}
