//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Microdiseno
    {
        public int Id { get; set; }
        public string CursoCodigo { get; set; }
        public string Semestre { get; set; }
        public string Facultad { get; set; }
        public string Modalidad { get; set; }
        public string TipoCredito { get; set; }
        public string TipoAsignatura { get; set; }
        public string Estado { get; set; }
        public string Version { get; set; }
        public string ElaboradoPor { get; set; }
        public string RevisadoPor { get; set; }
        public string AprobadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string ObservacionesRechazo { get; set; }
        public string ContenidoJSON { get; set; }
        public bool VisibleParaTodos { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaAval { get; set; }
    }
}
