//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MomentosEvaluativo
    {
        public int Id { get; set; }
        public int GrupoId { get; set; }
        public string EventoEvaluativo { get; set; }
        public string TipoEvento { get; set; }
        public decimal Ponderacion { get; set; }
        public string Fecha { get; set; }
    
        public virtual Grupos Grupos { get; set; }
    }
}
