//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MomentosEvaluativo
    {
        public int Id { get; set; }
        public int GrupoId { get; set; }
        public string EventoEvaluativo { get; set; }
        public string TipoEvento { get; set; }
        public decimal Ponderacion { get; set; }
        public string Fecha { get; set; }
    
        public virtual Grupos Grupos { get; set; }
    }
}
