//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA_Competencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RA_Competencia()
        {
            this.RA_Resultado = new HashSet<RA_Resultado>();
        }
    
        public int Id { get; set; }
        public int ProgramaId { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int Orden { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CreadoEn { get; set; }
        public System.DateTime ActualizadoEn { get; set; }
    
        public virtual RA_Programa RA_Programa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA_Resultado> RA_Resultado { get; set; }
    }
}
