//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA_Programa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RA_Programa()
        {
            this.RA_Version = new HashSet<RA_Version>();
            this.RA_Competencia = new HashSet<RA_Competencia>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string PerfilEgreso { get; set; }
        public string PerfilOcupacional { get; set; }
        public string TituloCompetencias { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CreadoEn { get; set; }
        public System.DateTime ActualizadoEn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA_Version> RA_Version { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA_Competencia> RA_Competencia { get; set; }
    }
}
