//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA_Version
    {
        public int Id { get; set; }
        public int ProgramaId { get; set; }
        public int Version { get; set; }
        public System.DateTime FechaCambio { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Accion { get; set; }
        public Nullable<int> VersionOrigen { get; set; }
        public string SnapshotJson { get; set; }
    
        public virtual RA_Programa RA_Programa { get; set; }
    }
}
