//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallaCurricular.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA_Version
    {
        public int Id { get; set; }
        public int ProgramaId { get; set; }
        public int Version { get; set; }
        public System.DateTime FechaCambio { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Accion { get; set; }
        public Nullable<int> VersionOrigen { get; set; }
        public string SnapshotJson { get; set; }
    
        public virtual RA_Programa RA_Programa { get; set; }
    }
}
